project:
  type: website
  output-dir: docs

website:
  title: "Shayna Sura"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: My Work
        menu: 
          - text: PhD
          - text: Dauphin Island Sea Lab
          - text: Gulf Ecosystem Initiative
      - icon: github
        href: https://github.com/shaynasura/shaynasura.github.io
          
      

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    # theme: cosmo
    # css: styles.css
    mainfont: Tajawal
    toc: true
    page-layout: full

editor: visual



