project:
  type: website
  output-dir: docs

website:
  title: "Shayna Sura"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: My Work
        menu: 
          - text: Mentoring
      - icon: github
        href: https://github.com/shaynasura/shaynasura.github.io
          
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual



